server:
  port: 8080
spring:
  application:
    name: zhiyin_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/zhiyin?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 20020112lzh.
  mail:
    #配置smtp服务主机地址
    host: smtp.qq.com
    #发送者邮箱
    username: 2940402378@qq.com
    #配置密码,注意不是真正的密码，而是刚刚申请到的授权码
    password: edqpgyfrhrncdega
    #端口号465或587
    port: 587
    #默认的邮件编码为UTF-8
    default-encoding: UTF-8
    #其他参数
    properties:
      mail:
        #配置SSL 加密工厂
        smtp:
          ssl:
            #本地测试，先放开ssl
            enable: false
            required: false
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true


#  #邮件配置（自定义设置，主要配置了收件人和发件人，这些可以当做发送邮件的参数）
#mail-config:
#    environmental: 邮件测试
#    # 发件人邮箱
#    from: 发件人@foxmail.com
#    # 收件人邮箱（抄送人）
#    recipient:
#      - "收件人1的邮箱@foxmail.com"
#      - "收件人2的邮箱@qq.com"

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

zhiyin:
  path: D:\zhiyin\



